	cd ..
	cd 好的格局

	fload             極向離明格.f
            fload             輔弼拱主格.f           
            fload             紫府同宮格.f 
            fload             紫府朝垣格.f           
            fload             巨機同臨格.f           
            fload             善蔭朝綱格.f           
            fload             機月同梁格.f           
            fload             日麗中天格.f            
            fload             日照雷門格.f            
            fload             日月同宮格.f           
            fload             日月並明格.f           
            fload              明珠出海格.f           
            fload             日月照璧格.f           
            fload             巨日同宮格.f           
            fload             陽梁昌祿格.f           
            fload             貪武同行格.f           
            fload             將星得地格.f           
            fload             財祿夾馬格.f           
            fload             廉貞文武格.f           
            fload             財蔭夾印格.f           
            fload             化星返貴格.f           
            fload             雄宿朝元格.f           
            fload             天府守垣格.f           
            fload             府相朝垣格.f           
            fload             月朗天門格.f           
            fload             月生滄海格.f           
            fload             火貪格.f           
            fload             鈴貪格.f           
            fload             石中隱玉格.f           
            fload             祿馬配印格.f           
            fload             祿馬交馳格.f           
            fload             壽星入廟格.f           
            fload             七殺朝斗格.f
            fload             英星入廟格.f           
            fload             文桂文華格.f           
            fload             文星拱命格.f           
            fload             昌曲夾命格.f           
            fload             左右同宮格.f           
            fload             輔拱文星格.f           
            fload             三奇嘉會格.f           
            fload             權祿巡逢格.f           
            fload             祿合鴛鴦格.f           
            fload             甲第登庸格.f           
            fload             科名會祿格.f           
            fload             擎羊入廟格.f           
            fload             坐貴向貴格.f           
            fload             天乙拱命格.f           
	cd ..